### ISSUE TITLE
Is there a way to disable having the user select columns?

### ISSUE THREAD

**Issue by gvanto** [redsquirrelstudio/laravel-backpack-import-operation#1]
I just want an import file field which takes a CSV and processes it - without having to let user map fields ... is this possible?

Thanks for a great package!

**Comment by redsquirrelstudio** [comment]
Hi there,

This isn't an option at the moment, but I can't imagine it would be too difficult to implement,

I'll get this worked on and added to the package,

Many thanks for the suggestion! Glad you're finding use out of the package :)
