### ISSUE TITLE
Class "Backpack\Generators\Services\BackpackCommand" not found 

### ISSUE THREAD

**Issue by arb362** [redsquirrelstudio/laravel-backpack-import-operation#17]
I was just deploying this to my staging environment and noticed that it was failing because the ImportColumnBackpackCommand extends a class from the backpack/generators package. 
That could be easily fixed by requiring the package or.....I wondered if in order to prevent requiring backpack/generators in a production environment it would be reasonable to only register the command in your ImportOperationProvider if the Class for the BackpackCommand existed. i.e.
`if (class_exists('\Backpack\Generators\Services\BackpackCommand')) {
         $this->commands($this->commands);
}`

**Comment by redsquirrelstudio** [comment]
Hi @arb362 

Thank you for the fix suggestion, this has been implemented in v1.6.7

Many thanks!
