### ISSUE TITLE
Custom parameters for custom type

### ISSUE THREAD

**Issue by rahman-nero** [redsquirrelstudio/laravel-backpack-import-operation#19]
Hello. I am creating my own custom column. While writing it, I got an issue. I can't access to any custom attributes that I set in setupImportOperation. 

Code:
```php
 protected function setupImportOperation()
    {
        $this->crud->addColumn([
            'name'  => 'name',
            'label' => 'Name',
            'type'  => 'text',
        ]);

        $this->crud->addColumn([
            'name'      => 'contrType',
            'label'     => '...',
            'type'      => RelationshipColumn::class,
            'attribute' => 'alias',
            'model'     => ToServiceTypeField::class,
        ]);
    }
```

RelationshipColumn:
```php
class RelationshipColumn extends ImportColumn
{
    /**
     * @return ?string
     */
    public function output(): mixed
    {
        dd($this->getConfig());

        return $this->data;
    }
}
```

Output:
```
array:3 [▼ // app/Imports/Columns/RelationshipColumn.php:14
  "name" => "contrType"
  "label" => "..."
  "type" => "App\Imports\Columns\RelationshipColumn"
]
```

It's a quite problem for me. I can't get any custom attributes that I passed. Is there any way to get them in the class?.

**Comment by redsquirrelstudio** [comment]
Hi @rahman-nero 

Apologies for the delay in getting this fixed, I didn't get a notification about your issue! 

I've now updated the operation so that it saves all column attributes rather than a filtered set, which should solve your problem. Let me know if that's all okay.

Please install v1.6.8 of the package. Many thanks for opening this issue!

**Comment by rahman-nero** [comment]
I appreciate fixing that. 

Cheers!

**Comment by redsquirrelstudio** [comment]
No worries at all @rahman-nero,

If you have the time, a star on the repo would be greatly appreciated :)
