### ISSUE TITLE
Column is not being set during import

### ISSUE THREAD

**Issue by gvanto** [redsquirrelstudio/laravel-backpack-import-operation#4]
Hi again @redsquirrelstudio,

I've followed all the Install steps, and got the following:

```
protected function setupImportOperation()
    {
        //makes no difference to issue
        //$this->disableUserMapping();

        CRUD::addColumn([
            'name' => 'source',
            'type' => 'text',
            'primary_key' => true
        ]);

        CRUD::addColumn([
            'name' => 'target',
            'type' => 'text',
        ]);

        CRUD::setValidation(RedirectRequest::class);
    }
```

But getting the following error when running the import (the only 2 columns I want to actually import - source, target - seem to be ignored in the upload):

![image](https://github.com/redsquirrelstudio/laravel-backpack-import-operation/assets/8372918/cf5d7a1f-2d5f-4241-a496-30aed449d13e)

The Redirect class:

```
<?php

namespace App\Models;

use Backpack\CRUD\app\Models\Traits\CrudTrait;
use App\Services\DynamoDbService;
use Carbon\CarbonInterface;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

/**
 * @property int $id
 * @property int $user_id
 * @property User $user
 * @property string $source
 * @property string $target
 * @property CarbonInterface $created_at
 * @property CarbonInterface $updated_at
 */
class Redirect extends Model
{
    use CrudTrait;

    protected $fillable = [
        'source',
        'target',
        'user_id',
    ];

    public function user(): BelongsTo
    {
        return $this->belongsTo(User::class);
    }
}
```

File being uploaded, redirects-test.csv:

> source,target
> /foo1,/bar1
> /foo2,/bar2
> /foo3,/bar3

**Comment by gvanto** [comment]
Interestingly, when I add the 'label' to the columns,

```
CRUD::addColumn([
            'name' => 'source',
            'label' => 'Source',
            'type' => 'text',
            'primary_key' => true
        ]);

        CRUD::addColumn([
            'name' => 'target',
            'label' => 'Target',
            'type' => 'text',
        ]);
```

the import proceeds (and I get "import was successful"), but the import has not actually worked (no records were imported)...

**Comment by redsquirrelstudio** [comment]
Hi @gvanto 

Thank you for sending through these issues, these are massively helpful.

I have published a new version (1.6.1) which resolves this problem,

Please let me know whether the imports are now being processed successfully.

With many thanks,

Lewis

**Comment by karandatwani92** [comment]
The latest release solved it. Thanks @redsquirrelstudio

**Comment by gvanto** [comment]
Hi @redsquirrelstudio 

I've updated package version but still no luck (exact same issue as before, says import successful but it's not)

![image](https://github.com/redsquirrelstudio/laravel-backpack-import-operation/assets/8372918/f7a5c8b6-872f-4209-b73a-28c8c458a244)

Wondering if it's importing of the file issue?

I have in imports.php:
<img width="775" alt="image" src="https://github.com/redsquirrelstudio/laravel-backpack-import-operation/assets/8372918/87daab6d-ad8c-4015-b892-dd56afd0fc68">

and I've created that folder and set its permission to 777, but not seeing a file in there after the import ...

**Comment by gvanto** [comment]
OK so interestingly, it works but only with the following enabled:

`$this->disableUserMapping();`

**Comment by redsquirrelstudio** [comment]
Hi @gvanto 

Please run php artisan tinker and enter

```php
config('backpack.operations.import');
```

Then send through the output,

Many thanks!

**Comment by gvanto** [comment]
> Hi @gvanto
> 
> Please run php artisan tinker and enter
> 
> ```
> config('backpack.operations.import');
> ```
> 
> Then send through the output,
> 
> Many thanks!

Sure Lewis, here it is (although I don't think it's the issue, see my [previous message](https://github.com/redsquirrelstudio/laravel-backpack-import-operation/issues/4#issuecomment-1893778813))

![image](https://github.com/redsquirrelstudio/laravel-backpack-import-operation/assets/8372918/14e1e3d9-dd5b-42cd-984c-305e07f4578f)

**Comment by gvanto** [comment]
> The latest release solved it. Thanks @redsquirrelstudio

@karandatwani92 
Are you using this?

`$this->disableUserMapping();`

**Comment by karandatwani92** [comment]
@gvanto For me It's working with & without`$this->disableUserMapping();`

**Comment by redsquirrelstudio** [comment]
@karandatwani92 Thank you for confirming :)

@gvanto could you please send through the full contents of your
```php
setupImportOperation
```

**Comment by gvanto** [comment]
> @karandatwani92 Thank you for confirming :)
> 
> @gvanto could you please send through the full contents of your
> 
> ```
> setupImportOperation
> ```

Just rebuilt my docker, and re-tested, still not working with below:

```
protected function setupImportOperation()
    {
        //$this->disableUserMapping();

        CRUD::addColumn([
            'name' => 'source',
            'label' => 'Source',
            'type' => 'text',
            'primary_key' => true
        ]);

        CRUD::addColumn([
            'name' => 'target',
            'label' => 'Target',
            'type' => 'text',
        ]);

        CRUD::setValidation(RedirectRequest::class);
    }
```

**Comment by redsquirrelstudio** [comment]
@gvanto 

Thank you for sending that through,

I have fully replicated your config and have managed to complete an import using disableUserMapping(); and without

Can I confirm two things:
- You are going through all of the user mapping steps, (Import file, map fields, confirm)
- You are using a standard database such as sql that uses a driver which ships with Laravel (I note that your model mentions a dynamo db service).

Many thanks

**Comment by gvanto** [comment]
Hi @redsquirrelstudio,

I am going through the user mapping steps yes.

Yup, standard MySQL database for Redirect model. (The dynamodb stuff is unrelated)

FYI, the import_log even creates a record upon import.
But the laravel.log file has nothing, and the records don't actually import for me. Very strange.

For now I guess will just disable the user mapping (especially since I asked for this feature to begin with 😄 thanks again for it).

How do I open a feature request? What would be amazing is a simple CSV EXPORT button (next to the import button) :D :D

**Comment by redsquirrelstudio** [comment]
Hi @gvanto 

Really strange, sorry I can't help further with that issue,

For a feature request, just open another issue, explaining the full feature

I'll label it as such :)

Have a good rest of the day!
