### ISSUE TITLE
Feature - Update Validation Behaviour

### ISSUE THREAD

**Issue by redsquirrelstudio** [redsquirrelstudio/laravel-backpack-import-operation#8]
## Current behaviour 
Validation currently validates each row of the imported  file. If a row fails it is not imported.

## Proposed behaviour
As suggested by @karandatwani92 Validation should update the user mapping view with red asterisks when columns are required. It should also prevent a file from being imported if these columns are not mapped.  (Or not present in the case of a simple mapping disabled import).

I do not think that in the current version validation should use other rules to stop a file being imported. As this would require a full scan of the file before it is imported.

**Comment by karandatwani92** [comment]
Hey @redsquirrelstudio
I misunderstood the current validation. Now, I know it applies to rows & skips them. This is good!
Also, this made me wonder how the user would know - which rows were skipped.

I didn't mean the full scan. I mean just simple validation while mapping so the user doesn't forget to map.

**Comment by redsquirrelstudio** [comment]
No problem at all, just mentioned a full scan in case anyone looks up this issue in the future :)

Maybe it would be worth creating an event that returns the number of successful and unsuccessful rows on completion or something similar?

**Comment by redsquirrelstudio** [comment]
Hi @karandatwani92,

Version 1.6.4 has been published including the updated validation behaviour :)

**Comment by gvanto** [comment]
> No problem at all, just mentioned a full scan in case anyone looks up this issue in the future :)
> 
> Maybe it would be worth creating an event that returns the number of successful and unsuccessful rows on completion or something similar?

This is a great idea - did this event get incorporated?
Then the skipped rows can be added to the flash message and displayed after upload so that user is aware which rows didn't upload.
